export const SET_DARK = "SET_DARK";

export const SET_USER = "SET_USER";
export const UPDATE_USER = "UPDATE_USER";

export const GET_DOCTORS = "GET_DOCTORS";

export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const UPDATE_APPOINTMENTS = "UPDATE_APPOINTMENTS";

export const APPEND_MESSAGES = "APPEND_MESSAGES";
export const UPDATE_CONVERSATION = "UPDATE_CONVERSATION";
export const UPDATE_CONVERSATIONS = "UPDATE_CONVERSATIONS";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const PREPEND_MESSAGES = "PREPEND_MESSAGES";
export const SET_SOCKET_STATUS = "SET_SOCKET_STATUS";
export const USER_TYPING = "USER_TYPING";